[project]
name = "pddlsim"
version = "0.2.0"
description = "PDDL-based simulator for the BIU course \"Introduction to Intelligent, Knowledge-Based and Cognitive Systems\""
authors = [
    { name = "Gal A. Kaminka", email = "galk@cs.biu.ac.il" },
    { name = "Micha S. Molko", email = "michamolko@gmail.com" },
    { name = "Ron Shemesh", email = "ron.shemesh98@gmail.com" },
    { name = "Eyal Weiss", email = "eyal.weiss@biu.ac.il" },
    { name = "Mika Barkan", email = "mika.barkan4@gmail.com" },
    { name = "Yoav Grimland", email = "miestrode@proton.me" },
]
dependencies = [
    "unified-planning>=1.1.0,<2",
    "unified-planning[fast-downward]",
    "numpy<2", # Update this once ConfigSpace works with NumPy 2.x.x
    "setuptools>=70.2.0,<71",
]
requires-python = ">=3.12,<4"
readme = "README.md"
license = { text = "MIT" }
keywords = ["PDDL", "agent", "simulator"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Programming Language :: Python :: 3 :: Only",
]

[project.urls]
Repository = "https://bitbucket.org/galk-opensource/executionsimulation/"
Issues = "https://bitbucket.org/galk-opensource/executionsimulation/issues"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.dev-dependencies]
test = [
    "pytest>=8.2.2,<9",
    "pytest-benchmark>=4.0.0,<5",
    "pytest-benchmark[histogram]"
]
doc = [
    "sphinx>=7.3.7,<8",
    "pydata-sphinx-theme>=0.15.3,<0.16",
    "sphinx-design>=0.6.0,<0.7",
]
format = [
    "black>=24.4.2, <25",
]

[tool.pytest.ini_options]
testpaths = [
    "tests/*.py",
    "tests/benches/*.py"
]
filterwarnings = [
    "ignore::DeprecationWarning",
]
# See: https://pytest-benchmark.readthedocs.io/en/latest/usage.html#commandline-options
addopts = "-ra --benchmark-skip --benchmark-autosave"