(define (problem two-balls)
    (:domain gripper)
    (:objects rooma roomb - room ball1 ball2 - ball left right - gripper)
    (:init (at-robby rooma)
           (free left)
           (free right)
           (at ball1 rooma)
           (at ball2 rooma))
    (:goal (at ball1 roomb)))