name: Release to Test PyPI

on:
  release:
    types: ["published"]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          # Install a specific version of uv.
          version: "0.7.12"
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Build the project
        run: uv build

      - name: Publish
        run: uv publish --trusted-publishing --url https://test.pypi.org/legacy/